# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
jobs:
  mkdocs:
    name: Build mkdocs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v0.24
